// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTruequeU.Data;

#nullable disable

namespace PTruequeU.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521001324_UpdateUserNames")]
    partial class UpdateUserNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "11111111-aaaa-1111-aaaa-111111111111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "22222222-bbbb-2222-bbbb-222222222222",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aaaaaaaa-aaaa-aaaa-aaaa-000000000000",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PTruequeU.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP-STATIC-000000000000000",
                            Email = "admin@email.com",
                            EmailConfirmed = true,
                            FullName = "Administrador",
                            IsSuspended = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENx4zxiRrAfPtkZV5vFfJ+RgEHgHrAvRjf6bdYMLzInq/XWu7gibD/0GBKoPO3EBEg==",
                            PhoneNumberConfirmed = false,
                            ProgramName = "Administración",
                            Rating = 0.0,
                            SecurityStamp = "SECSTAMP-STATIC-0000000000000000",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP-STATIC-000000000000001",
                            Email = "andrea@email.com",
                            EmailConfirmed = true,
                            FullName = "Andrea García",
                            IsSuspended = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANDREA@EMAIL.COM",
                            NormalizedUserName = "ANDREA",
                            PasswordHash = "AQAAAAIAAYagAAAAENx4zxiRrAfPtkZV5vFfJ+RgEHgHrAvRjf6bdYMLzInq/XWu7gibD/0GBKoPO3EBEg==",
                            PhoneNumberConfirmed = false,
                            ProgramName = "Ingeniería de Sistemas",
                            Rating = 0.0,
                            SecurityStamp = "SECSTAMP-STATIC-0000000000000001",
                            TwoFactorEnabled = false,
                            UserName = "andrea"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP-STATIC-000000000000002",
                            Email = "bruno@email.com",
                            EmailConfirmed = true,
                            FullName = "Bruno Martínez",
                            IsSuspended = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BRUNO@EMAIL.COM",
                            NormalizedUserName = "BRUNO",
                            PasswordHash = "AQAAAAIAAYagAAAAENx4zxiRrAfPtkZV5vFfJ+RgEHgHrAvRjf6bdYMLzInq/XWu7gibD/0GBKoPO3EBEg==",
                            PhoneNumberConfirmed = false,
                            ProgramName = "Administración de Empresas",
                            Rating = 0.0,
                            SecurityStamp = "SECSTAMP-STATIC-0000000000000002",
                            TwoFactorEnabled = false,
                            UserName = "bruno"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONCSTAMP-STATIC-000000000000003",
                            Email = "carla@email.com",
                            EmailConfirmed = true,
                            FullName = "Carla López",
                            IsSuspended = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLA@EMAIL.COM",
                            NormalizedUserName = "CARLA",
                            PasswordHash = "AQAAAAIAAYagAAAAENx4zxiRrAfPtkZV5vFfJ+RgEHgHrAvRjf6bdYMLzInq/XWu7gibD/0GBKoPO3EBEg==",
                            PhoneNumberConfirmed = false,
                            ProgramName = "Diseño Industrial",
                            Rating = 0.0,
                            SecurityStamp = "SECSTAMP-STATIC-0000000000000003",
                            TwoFactorEnabled = false,
                            UserName = "carla"
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.Category", b =>
                {
                    b.Property<Guid>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            Name = "Electrónica"
                        },
                        new
                        {
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            Name = "Hogar"
                        },
                        new
                        {
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            Name = "Ropa"
                        },
                        new
                        {
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            Name = "Deportes"
                        },
                        new
                        {
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            Name = "Libros"
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sender_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Thread_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatMessage_Id");

                    b.HasIndex("Sender_Id");

                    b.HasIndex("Thread_Id");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000001"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Hola, ¿el celular sigue disponible?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000001")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000002"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 10, 10, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, está disponible. ¿Tienes alguna duda?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000001")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000003"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 10, 10, 8, 0, 0, DateTimeKind.Utc),
                            Text = "¿Aceptas algo menos de precio?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000001")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000004"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿El Samsung tiene algún golpe o rallón?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000002")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000005"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 11, 9, 3, 0, 0, DateTimeKind.Utc),
                            Text = "Ninguno, está impecable.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000002")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000006"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Cuál es la autonomía de batería de la laptop?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000003")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000007"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 12, 14, 10, 0, 0, DateTimeKind.Utc),
                            Text = "Unas 5 horas de uso normal.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000003")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000008"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 13, 8, 30, 0, 0, DateTimeKind.Utc),
                            Text = "¿La laptop tiene Windows original instalado?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000004")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000009"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 13, 8, 35, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, Windows 11 activado y sin problemas.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000004")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000010"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Los audífonos vienen con estuche original?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000005")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000011"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 14, 11, 6, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, estuche, cable y adaptador incluidos.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000005")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000012"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿La silla soporta más de 100kg?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000007")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000013"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 15, 16, 4, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, hasta 130kg según el fabricante.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000007")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000014"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Puedes bajar un poco el precio de la silla?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000008")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000015"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 16, 10, 7, 0, 0, DateTimeKind.Utc),
                            Text = "Te la dejo en 75.000 si cerramos hoy.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000008")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000016"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 17, 13, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿El sofá se puede desmontar para transportarlo?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000009")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000017"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 17, 13, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, en partes cabe sin problema en un auto mediano.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000009")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000018"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Cuánto tiempo tiene de uso la cafetera?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000011")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000019"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 18, 9, 4, 0, 0, DateTimeKind.Utc),
                            Text = "La compré hace 4 meses, tiene muy poco uso.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000011")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000020"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿La chaqueta es de cuero genuino o sintético?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000012")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000021"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 19, 10, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Es cuero genuino, tengo la factura original.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000012")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000022"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            SentAt = new DateTime(2023, 1, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿La bici tiene cambios Shimano?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000016")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000023"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 20, 15, 3, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, Shimano Altus de 21 velocidades.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000016")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000024"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Hacen envío o solo retiro en persona?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000017")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000025"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 21, 10, 6, 0, 0, DateTimeKind.Utc),
                            Text = "Solo retiro, la bici es muy voluminosa.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000017")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000026"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Las mancuernas son de hierro fundido?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000018")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000027"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 22, 8, 5, 0, 0, DateTimeKind.Utc),
                            Text = "Sí, con recubrimiento de goma antideslizante.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000018")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000028"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            SentAt = new DateTime(2023, 1, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿Clean Code trae ejercicios prácticos?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000019")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000029"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 23, 11, 8, 0, 0, DateTimeKind.Utc),
                            Text = "Tiene ejemplos de código reales en cada capítulo.",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000019")
                        },
                        new
                        {
                            ChatMessage_Id = new Guid("ffffffff-ffff-ffff-ffff-000000000030"),
                            Sender_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            SentAt = new DateTime(2023, 1, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            Text = "¿El libro de C# cubre .NET 6 o superior?",
                            Thread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000020")
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.ChatThread", b =>
                {
                    b.Property<Guid>("ChatThread_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Buyer_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Listing_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Seller_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ChatThread_Id");

                    b.HasIndex("Buyer_Id");

                    b.HasIndex("Seller_Id");

                    b.HasIndex("Listing_Id", "Buyer_Id", "Seller_Id")
                        .IsUnique();

                    b.ToTable("ChatThreads");

                    b.HasData(
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000001"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000002"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000003"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000004"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000005"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000006"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000007"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000008"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000009"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000010"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000011"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000007"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000012"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000013"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000014"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000009"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000015"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000010"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000016"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            CreatedAt = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000017"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000018"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000012"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000019"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            CreatedAt = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000014"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            ChatThread_Id = new Guid("eeeeeeee-eeee-eeee-eeee-000000000020"),
                            Buyer_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            CreatedAt = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000015"),
                            Seller_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.Favorite", b =>
                {
                    b.Property<Guid>("Favorite_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Listing_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Favorite_Id");

                    b.HasIndex("Listing_Id");

                    b.HasIndex("User_Id", "Listing_Id")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PTruequeU.Models.Listing", b =>
                {
                    b.Property<Guid>("Listing_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Category_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Listing_id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Excelente estado, cargador original incluido.",
                            IsHidden = false,
                            Location = "",
                            Price = 120000m,
                            State = 0,
                            Title = "Celular Samsung Galaxy A54",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intel i5, 8GB RAM, SSD 256GB, sin golpes.",
                            IsHidden = false,
                            Location = "",
                            Price = 350000m,
                            State = 0,
                            Title = "Laptop HP Pavilion 15",
                            UpdatedAt = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancelación de ruido activa, poco uso.",
                            IsHidden = false,
                            Location = "",
                            Price = 95000m,
                            State = 0,
                            Title = "Audífonos Sony WH-1000XM4",
                            UpdatedAt = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pantalla 10 pulgadas, 64GB, con funda protectora.",
                            IsHidden = false,
                            Location = "",
                            Price = 85000m,
                            State = 0,
                            Title = "Tablet Lenovo Tab M10",
                            UpdatedAt = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonómica, reposapiés incluido, color negro/rojo.",
                            IsHidden = false,
                            Location = "",
                            Price = 80000m,
                            State = 0,
                            Title = "Silla gamer RGB",
                            UpdatedAt = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000006"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tela beige, sin manchas, desmontable.",
                            IsHidden = false,
                            Location = "",
                            Price = 180000m,
                            State = 0,
                            Title = "Sofá de 3 puestos",
                            UpdatedAt = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000007"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uso doméstico, incluye jarra de leche.",
                            IsHidden = false,
                            Location = "",
                            Price = 45000m,
                            State = 0,
                            Title = "Cafetera espresso Oster",
                            UpdatedAt = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000008"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Talla M, muy poco uso, estilo biker.",
                            IsHidden = false,
                            Location = "",
                            Price = 60000m,
                            State = 0,
                            Title = "Chaqueta de cuero negra",
                            UpdatedAt = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000009"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Talla 32x32, corte slim, azul oscuro.",
                            IsHidden = false,
                            Location = "",
                            Price = 35000m,
                            State = 0,
                            Title = "Jeans Levi's 511",
                            UpdatedAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000010"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Talla 42, usadas 3 veces, blanco/gris.",
                            IsHidden = false,
                            Location = "",
                            Price = 70000m,
                            State = 0,
                            Title = "Zapatillas Nike Air Max 90",
                            UpdatedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rodada 29, frenos hidráulicos, 21 velocidades.",
                            IsHidden = false,
                            Location = "",
                            Price = 250000m,
                            State = 0,
                            Title = "Bicicleta de montaña Trek",
                            UpdatedAt = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000012"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Par completo con barra y discos, recubrimiento goma.",
                            IsHidden = false,
                            Location = "",
                            Price = 55000m,
                            State = 0,
                            Title = "Mancuernas ajustables 20kg",
                            UpdatedAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000013"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Head 100, grip 4, en funda original.",
                            IsHidden = false,
                            Location = "",
                            Price = 40000m,
                            State = 0,
                            Title = "Raqueta de tenis Wilson",
                            UpdatedAt = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000014"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edición en español, marcas de lápiz leves.",
                            IsHidden = false,
                            Location = "",
                            Price = 25000m,
                            State = 0,
                            Title = "Libro Clean Code",
                            UpdatedAt = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002"
                        },
                        new
                        {
                            Listing_id = new Guid("cccccccc-cccc-cccc-cccc-000000000015"),
                            Category_Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            Condition = 0,
                            CreatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4ta edición, como nuevo, sin subrayados.",
                            IsHidden = false,
                            Location = "",
                            Price = 30000m,
                            State = 0,
                            Title = "Libro C# en Profundidad",
                            UpdatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            User_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001"
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.ListingImage", b =>
                {
                    b.Property<Guid>("ListingImage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Listing_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListingImage_Id");

                    b.HasIndex("Listing_Id");

                    b.ToTable("ListingImages");

                    b.HasData(
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000001"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000002"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000003"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000004"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000005"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000006"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000007"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000008"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000009"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000010"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000011"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000012"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1605296867424-35fc25c9212a?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000013"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000014"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000006")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000015"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000007")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000016"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000007")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000017"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000018"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000019"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000009")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000020"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1475178626620-a4d074967452?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000009")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000021"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000010")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000022"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000010")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000023"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000024"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000025"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000026"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000012")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000027"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000012")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000028"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1617083934551-ac453d8f7097?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000013")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000029"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1551773188-0801da12ddae?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000013")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000030"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000014")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000031"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000014")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000032"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000015")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000033"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000015")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000034"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000015")
                        },
                        new
                        {
                            ListingImage_Id = new Guid("dddddddd-dddd-dddd-dddd-000000000035"),
                            DisplayOrder = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400",
                            Listing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        });
                });

            modelBuilder.Entity("PTruequeU.Models.ModerationAction", b =>
                {
                    b.Property<Guid>("ModerationAction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Admin_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ModerationAction_Id");

                    b.HasIndex("Admin_Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetId");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("PTruequeU.Models.Report", b =>
                {
                    b.Property<Guid>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportedListing_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportedUser_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Reporter_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.HasKey("Report_Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportedListing_Id");

                    b.HasIndex("ReportedUser_Id");

                    b.HasIndex("Reporter_Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Comment = "El precio es demasiado bajo para ese modelo, posible robo.",
                            CreatedAt = new DateTime(2023, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Precio sospechoso",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Comment = "Me pidió hacer la transferencia fuera de la plataforma.",
                            CreatedAt = new DateTime(2023, 1, 14, 11, 30, 0, 0, DateTimeKind.Utc),
                            Reason = "Intento de estafa",
                            ReportedUser_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Comment = "Hay 3 publicaciones idénticas de este usuario.",
                            CreatedAt = new DateTime(2023, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Publicación duplicada",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Comment = "Las fotos no corresponden al producto que se entrega.",
                            CreatedAt = new DateTime(2023, 1, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Descripción engañosa",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Comment = "Envió mensajes ofensivos durante la negociación del precio.",
                            CreatedAt = new DateTime(2023, 1, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            Reason = "Comportamiento inapropiado",
                            ReportedUser_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Comment = "La chaqueta tiene logos de marca que parecen réplica.",
                            CreatedAt = new DateTime(2023, 1, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Artículo falsificado",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000008"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Comment = "El vendedor confirmó que fue vendido pero la publicación sigue.",
                            CreatedAt = new DateTime(2023, 1, 25, 10, 15, 0, 0, DateTimeKind.Utc),
                            Reason = "Producto ya vendido",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Comment = "Parece ser una copia no autorizada, no el original.",
                            CreatedAt = new DateTime(2023, 1, 27, 13, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Derechos de autor",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000014"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000001",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000009"),
                            Comment = "El perfil parece ser un bot, respuestas automáticas y rápidas.",
                            CreatedAt = new DateTime(2023, 1, 29, 9, 30, 0, 0, DateTimeKind.Utc),
                            Reason = "Cuenta sospechosa",
                            ReportedUser_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000002",
                            TargetType = 0
                        },
                        new
                        {
                            Report_Id = new Guid("11111111-1111-1111-1111-000000000010"),
                            Comment = "El mismo libro nuevo cuesta menos en cualquier librería física.",
                            CreatedAt = new DateTime(2023, 2, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Precio inflado",
                            ReportedListing_Id = new Guid("cccccccc-cccc-cccc-cccc-000000000015"),
                            Reporter_Id = "aaaaaaaa-aaaa-aaaa-aaaa-000000000003",
                            TargetType = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTruequeU.Models.ChatMessage", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("Sender_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("Thread_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("PTruequeU.Models.ChatThread", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", "Buyer")
                        .WithMany()
                        .HasForeignKey("Buyer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("Listing_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("Seller_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("PTruequeU.Models.Favorite", b =>
                {
                    b.HasOne("PTruequeU.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("Listing_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTruequeU.Models.Listing", b =>
                {
                    b.HasOne("PTruequeU.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PTruequeU.Models.ApplicationUser", "User")
                        .WithMany("Listings")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTruequeU.Models.ListingImage", b =>
                {
                    b.HasOne("PTruequeU.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("Listing_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PTruequeU.Models.ModerationAction", b =>
                {
                    b.HasOne("PTruequeU.Models.ApplicationUser", "Admin")
                        .WithMany()
                        .HasForeignKey("Admin_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PTruequeU.Models.Report", b =>
                {
                    b.HasOne("PTruequeU.Models.Listing", "ReportedListing")
                        .WithMany()
                        .HasForeignKey("ReportedListing_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTruequeU.Models.ApplicationUser", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUser_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTruequeU.Models.ApplicationUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("Reporter_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedListing");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("PTruequeU.Models.ApplicationUser", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("PTruequeU.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("PTruequeU.Models.ChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PTruequeU.Models.Listing", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
